In [3]:
import numpy as np
# Discovering numpy
# create a rank 1 dimensional array
arr = np.array([1,2,3])         # 
print(type(arr))                # class numpy.ndarray
print(arr.dtype)                # int64
print(arr.shape)                # (3,)
print(arr[0], arr[1], arr[2])   # 1 2 3 
arr[2] = 4                      # changes the last element [2], to 4
print(arr)                      # [1 2 4]

# make a rank 2 array
arr2 = np.array([[1,2,3],[4,5,6]])      
print(arr2.shape)                       # (2, 3)
print(arr2[0,0], arr2[0,1], arr2[1,0])  # 1 2 4
print(arr2[-1])                         # only printing the last element(hence the negative)  [4 5 6]



# to generate arrays in a different way with numpy
# create array of zeros with two dimensions and a size of 2
zero = np.zeros((2,2))
print(zero)
# [[0. 0.]
# [0. 0.]]

# create an array of ones with one dimension and size of two
one = np.ones((1,2))
print(one)
# 5 5
# 5 5

# create an array with a given shape, type, and with value
constant = np.full((2,2),5)
print(constant)
# three rows
# 1. 0. 0.
# 0. 1. 0.
# 0. 0. 1.


# create a 2 dimensional array with one on diagonal and 0 on others
diag = np.eye(4,k=1)
print(diag)
# four rows
# 0. 1. 0. 0.
# 0. 0. 1. 0.
# 0. 0. 0. 1.
# 0. 0. 0. 0.

# create an array of random values
rand = np.random.random((2,2))
print(rand)
# two by two of random numbers
# wow this is pretty cool

<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.18394881 0.36553124]
 [0.28486356 0.27578173]]


In [ ]:
# array indexing
arr = np.arange(10)  # generating array [0 1 2 3 4 5 6 7 8 9]
print(arr[0:8:2])   # print every two number from 0 but before 8

# create a rank 2 with shape (3,4) array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[:2,:2])           # [[1 2]
                            #  [5 6]]

# indexing integers
arr = np.array([[1,2],[3,4],[5,6]])
print(arr[[0,1,2],[0,1,1]])             
# [1 4 6]
